version: '2.23.3-desktop.2'
services:

  api:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: fast_api
    command: ["/fastapp/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:15.1-alpine
    container_name: db
    command: -p 5454
    expose:
      - 5454
    env_file:
      - .env-docker

