version: '2.23.3-desktop.2'
services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    command: -p 5454
    expose:
      - 5454
    env_file:
      - .env-docker

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env-docker
    container_name: tests
    depends_on:
      - db
    command: [ "sh", "-c", " sleep 5 && sleep 3 && pytest /fastapp/src/tests"]

  redis:
    image: redis:7
    container_name: redis_db
    ports:
      - "6379:6379"
