version: '2.23.3-desktop.2'
services:

  api:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: fast_api
    command: ["/fastapp/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:15.1-alpine
    container_name: db
    command: -p 5454
    expose:
      - 5454
    env_file:
      - .env-docker

  db_test:
    image: postgres:15.1-alpine
    container_name: db_test
    command: -p 5455
    expose:
      - 5455
    env_file:
      - .env-docker

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env-docker
    container_name: tests
    depends_on:
      - api
    command: ["sh", "-c", "sleep 5 && pytest /fastapp/src/test"]