"""initial

Revision ID: 4ef5dae8c7fd
Revises:
Create Date: 2024-02-12 21:37:15.818528

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ef5dae8c7fd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=150), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=True),
                    sa.Column('manual_id', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('manual_id')
                    )
    op.create_table('submenus',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=150), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=True),
                    sa.Column('menu_id', sa.UUID(), nullable=True),
                    sa.Column('manual_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('manual_id')
                    )
    op.create_table('dishes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=150), nullable=False),
                    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=True),
                    sa.Column('submenu_id', sa.UUID(), nullable=True),
                    sa.Column('manual_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['submenu_id'], ['submenus.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('manual_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    op.drop_table('submenus')
    op.drop_table('menus')
    # ### end Alembic commands ###
